name: comment-on-issue

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install
      
      - name: run script
        run: npm run start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          COMMENT_CONFIG: ${{ vars.COMMENT_CONFIG }}
